#!/usr/bin/env python

import os
from datetime import datetime

# Please write your screenshot dir with full path.
screenshot_dir    = "/path/to/screenshot/directory"
os.chdir(screenshot_dir)
image_file     = datetime.now().strftime("Screenshot-ImageMagick-%Y-%m-%d_%H-%M-%S.png")
color_profile     = "/usr/share/color/icc/colord/sRGB.icc"
border_size       = "0"
background_color  = "white" # "none" for transparent; Hex color use "'#ffffff'"
background_size   = "20"
shadow_size       = "70x20+0+20"
color_fg          = "#666666"
color_bg          = "#666666"

os.system(f"""
flameshot gui --raw > {image_file}

magick convert {image_file} -bordercolor '{color_bg}' -border {border_size} \
{image_file} \

magick convert {image_file} \\( +clone -background black \
-shadow {shadow_size} \\) +swap -background none \
-layers merge +repage {image_file} \

magick convert {image_file} -bordercolor {background_color} \
-border {background_size} {image_file} \

magick convert {image_file} -gravity South -chop 0x{int(background_size)/2} \
{image_file} \

magick convert {image_file} -gravity North -background {background_color} \
-splice 0x{int(background_size)/2} {image_file} \

magick convert {image_file} -profile {color_profile} {image_file} \
""")